[project]
name = 'apitofsim'
version = '0.0.1'
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy", "pandas"]

[build-system]
build-backend = 'mesonpy'
requires = ["meson-python"]

[dependency-groups]
dev = [
    "meson-python>=0.18.0",
    "pip>=25.2",
]

[tool.meson-python.args]
setup = ['-Dpython=enabled']
